name: "Setup node and pnpm"
author: "Dafnik"
description: "Setup node, pnpm and the caching"
branding:
  icon: 'arrow-down-circle'
  color: 'purple'

inputs:
  pnpm:
    description: 'PNPM version'
    required: false
    default: 8
  node:
    description: "Node version"
    required: false
    default: 18
  install:
    description: "Runs pnpm install"
    required: false
    default: 'false'
  install-ignore-scripts:
    description: "Runs pnpm install --ignore-scripts"
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: use pnpm ${{ inputs.pnpm }}
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpm }}
  
    - name: use Node.js ${{ inputs.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node }}
        cache: 'pnpm'
        
    - name: get pnpm store directory
      id: pnpm-dir
      shell: bash
      run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      id: pnpm-cache
      name: setup pnpm cache
      with:
        path: ${{ steps.pnpm-dir.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Run pnpm install
      if: "${{ inputs.install == 'true' }}"
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Run pnpm install --ignore-scripts
      if: "${{ inputs.install-ignore-scripts == 'true' }}"
      shell: bash
      run: pnpm install --frozen-lockfile --ignore-scripts
